#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{


	enum class WINMODE { FULL, WIN };
	enum class RENDERGROUP { PRIORITY,NONBLEND, NONLIGHT,BLEND, BLOCKER, UI, ICON,END };
	enum class STATE { RIGHT, UP, LOOK, POSITION, END };
	enum class D3DTS { VIEW, PROJ, END };
	enum class DIMK { LBUTTON, RBUTTON, WHEEL, END };
	enum class DIMM { X, Y, WHEEL, END };
	enum class LIGHT { DIRECTIONAL, POINT,SPOT, END };
	enum class MODEL { NONANIM, ANIM, END };
	enum class DEFERRED { DEBUG, DIRECTIONAL, POINT,COMBINED, SPOT, BRIGHT,BLUR_X, BLUR_Y,FINAL,END };
	enum CHANNELID { SOUND_BGM, SOUND_EFFECT, SOUND_EFFECT_ENVIRONMENT,SOUND_EFFECT_PLAYER, SOUND_EFFECT_ZOMBIE, MAXCHANNEL };


}
#endif // Engine_Enum_h__
